
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INSTRUCTION_LDR INSTRUCTION_MOV INSTRUCTION_ADD INSTRUCTION_SUB INSTRUCTION_MUL INSTRUCTION_LDRB INSTRUCTION_CMP INSTRUCTION_BEQ INSTRUCTION_B INSTRUCTION_BLT INSTRUCTION_DCB INSTRUCTION_DCD INSTRUCTION_SPACE REGISTER REGISTER_ADDR NUMBER COMMENT LABEL LABEL_REFexpression : expression COMMENTexpression : LABELexpression : LABEL INSTRUCTION_DCB\n                  | LABEL INSTRUCTION_DCDexpression : LABEL INSTRUCTION_SPACEexpression : INSTRUCTION_LDR REGISTER NUMBERexpression : INSTRUCTION_LDR REGISTER REGISTER_ADDRexpression : INSTRUCTION_LDRB REGISTER REGISTER_ADDRexpression : INSTRUCTION_LDR REGISTER LABEL_REFexpression : INSTRUCTION_MOV REGISTER REGISTER\n                  | INSTRUCTION_MOV REGISTER NUMBERexpression : INSTRUCTION_CMP REGISTER NUMBER\n                  | INSTRUCTION_CMP REGISTER REGISTERexpression : INSTRUCTION_B LABELexpression : INSTRUCTION_BEQ LABEL\n                  | INSTRUCTION_BLT LABELexpression : INSTRUCTION_ADD REGISTER REGISTER REGISTER\n                  | INSTRUCTION_SUB REGISTER REGISTER REGISTER\n                  | INSTRUCTION_MUL REGISTER REGISTER REGISTERexpression : INSTRUCTION_ADD REGISTER REGISTER NUMBER\n                  | INSTRUCTION_SUB REGISTER REGISTER NUMBER\n                  | INSTRUCTION_MUL REGISTER REGISTER NUMBER'
    
_lr_action_items = {'INSTRUCTION_BLT':([0,],[1,]),'COMMENT':([4,8,13,16,17,18,21,22,26,28,29,30,33,34,35,36,37,38,39,40,41,42,43,],[-2,22,-16,-4,-3,-5,-14,-1,-15,-12,-13,-8,-11,-10,-9,-6,-7,-22,-19,-21,-18,-20,-17,]),'INSTRUCTION_MUL':([0,],[2,]),'INSTRUCTION_BEQ':([0,],[12,]),'INSTRUCTION_CMP':([0,],[3,]),'LABEL_REF':([25,],[35,]),'NUMBER':([15,24,25,27,31,32,],[28,33,36,38,40,42,]),'LABEL':([0,1,7,12,],[4,13,21,26,]),'INSTRUCTION_LDRB':([0,],[5,]),'INSTRUCTION_SUB':([0,],[6,]),'INSTRUCTION_DCD':([4,],[16,]),'$end':([4,8,13,16,17,18,21,22,26,28,29,30,33,34,35,36,37,38,39,40,41,42,43,],[-2,0,-16,-4,-3,-5,-14,-1,-15,-12,-13,-8,-11,-10,-9,-6,-7,-22,-19,-21,-18,-20,-17,]),'INSTRUCTION_SPACE':([4,],[18,]),'REGISTER':([2,3,5,6,9,10,11,14,15,20,23,24,27,31,32,],[14,15,19,20,23,24,25,27,29,31,32,34,39,41,43,]),'INSTRUCTION_B':([0,],[7,]),'INSTRUCTION_ADD':([0,],[9,]),'INSTRUCTION_MOV':([0,],[10,]),'INSTRUCTION_DCB':([4,],[17,]),'INSTRUCTION_LDR':([0,],[11,]),'REGISTER_ADDR':([19,25,],[30,37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression COMMENT','expression',2,'p_expression','sleeve.py',185),
  ('expression -> LABEL','expression',1,'p_label','sleeve.py',190),
  ('expression -> LABEL INSTRUCTION_DCB','expression',2,'p_databytes','sleeve.py',206),
  ('expression -> LABEL INSTRUCTION_DCD','expression',2,'p_databytes','sleeve.py',207),
  ('expression -> LABEL INSTRUCTION_SPACE','expression',2,'p_allocate_space','sleeve.py',213),
  ('expression -> INSTRUCTION_LDR REGISTER NUMBER','expression',3,'p_load','sleeve.py',219),
  ('expression -> INSTRUCTION_LDR REGISTER REGISTER_ADDR','expression',3,'p_load_addr','sleeve.py',224),
  ('expression -> INSTRUCTION_LDRB REGISTER REGISTER_ADDR','expression',3,'p_loadbyte','sleeve.py',229),
  ('expression -> INSTRUCTION_LDR REGISTER LABEL_REF','expression',3,'p_loadstring','sleeve.py',234),
  ('expression -> INSTRUCTION_MOV REGISTER REGISTER','expression',3,'p_mov','sleeve.py',239),
  ('expression -> INSTRUCTION_MOV REGISTER NUMBER','expression',3,'p_mov','sleeve.py',240),
  ('expression -> INSTRUCTION_CMP REGISTER NUMBER','expression',3,'p_compare','sleeve.py',245),
  ('expression -> INSTRUCTION_CMP REGISTER REGISTER','expression',3,'p_compare','sleeve.py',246),
  ('expression -> INSTRUCTION_B LABEL','expression',2,'p_branch','sleeve.py',251),
  ('expression -> INSTRUCTION_BEQ LABEL','expression',2,'p_branch_equal','sleeve.py',256),
  ('expression -> INSTRUCTION_BLT LABEL','expression',2,'p_branch_equal','sleeve.py',257),
  ('expression -> INSTRUCTION_ADD REGISTER REGISTER REGISTER','expression',4,'p_mads','sleeve.py',264),
  ('expression -> INSTRUCTION_SUB REGISTER REGISTER REGISTER','expression',4,'p_mads','sleeve.py',265),
  ('expression -> INSTRUCTION_MUL REGISTER REGISTER REGISTER','expression',4,'p_mads','sleeve.py',266),
  ('expression -> INSTRUCTION_ADD REGISTER REGISTER NUMBER','expression',4,'p_mads_value','sleeve.py',280),
  ('expression -> INSTRUCTION_SUB REGISTER REGISTER NUMBER','expression',4,'p_mads_value','sleeve.py',281),
  ('expression -> INSTRUCTION_MUL REGISTER REGISTER NUMBER','expression',4,'p_mads_value','sleeve.py',282),
]
